<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/05/16 15:05:31

return array(
'propel' => new sfPropelDatabase(array (
  'password' => 'BR9EanyEHBy8wKb9',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=sibum_prod;host=localhost',
  'username' => 'sibum_prod',
  'name' => 'propel',
)),);
