<?php
// auto-generated by sfRoutingConfigHandler
// date: 2009/05/16 15:05:32
return array(
'admin' => new sfRoute('/admin', array (
  'module' => 'admin',
  'action' => 'index',
), array (
), array (
)),
'save' => new sfRoute('/admin/save', array (
  'module' => 'admin',
  'action' => 'save',
), array (
), array (
)),
'delete' => new sfRoute('/admin/delete/:id', array (
  'module' => 'admin',
  'action' => 'delete',
), array (
), array (
)),
'search_target' => new sfRoute('/search', array (
  'module' => 'search',
  'action' => 'target',
), array (
), array (
)),
'answer' => new sfRoute(':target', array (
  'module' => 'answer',
  'action' => 'show',
), array (
), array (
)),
'homepage' => new sfRoute('/', array (
  'module' => 'search',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:action', array (
  'module' => 'answer',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
